### ISSUE TITLE
Security information missing when provisioning a sensor (Securing IoT northport)

### ISSUE THREAD

**Issue by cxzero** [Fiware/tutorials.PEP-Proxy#12]
Hi,

Hi, I am facing the same issue as #9 , still generating a trust token like https://github.com/FIWARE/tutorials.PEP-Proxy#oneseven-request.

The steps are:

**1. Generate a permanent token:**
```
curl -X POST \
  http://localhost:3005/oauth2/token \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic dHV0b3JpYWwtZGNrci1zaXRlLTAwMDAteHByZXNzd2ViYXBwOnR1dG9yaWFsLWRja3Itc2l0ZS0wMDAwLWNsaWVudHNlY3JldA==' \
  -d 'username=alice-the-admin@test.com&password=test&grant_type=password&scope=permanent'
```
`{"access_token":"1c385007ea9675490f37e3563fbb0d87fe1cbac8","token_type":"bearer","expires_in":3599,"refresh_token":"66f63fa5f9a6c3013191c15ae248776adc0c68fa","scope":["p"]}`

> In this case the scope is "p" and not "permanent" as in the tutorial, but perhaps it is because of an update in Keyrock 
> I also checked the "Token types" configuration for the "FIWARE Tutorial" app and "Permanent" is selected.

**2. Provision a trusted service group** (with above token)
```
curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Motion",
     "resource":    "/iot/d",
     "trust": "1c385007ea9675490f37e3563fbb0d87fe1cbac8"
   }
 ]
}'
```
> I am curious in this step if the cbroker URL is correct. **Should it be http://orion-proxy:1027?** 
> I changed it, but the error persists.

**3. IoT Agent - provisioning a sensor (error)**
```
curl -iX POST \
  'http://localhost:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion001",
     "entity_name": "urn:ngsi-ld:Motion:001",
     "entity_type": "Motion",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "c", "name": "count", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Store:001"}
     ]
   }
 ]
}
'
```
`{"name":"SECURITY_INFORMATION_MISSING","message":"Some security information was missing for device type:Motion"}`

> Should any additional header be added to this request? (tested with X-Auth-Token, Authorization but error remains)

Thanks in advance!
Regards,
Juan

**Comment by jason-fox** [comment]
It seems that the tutorial's service script has been updated to create the service groups on start-up. The POST request is correct if no service group had been corrected. The text has been amended as shown:

---

### IoT Agent - provisioning a trusted service group

The Access token (also known as a Trust Token) must be added to the service group. The `resource` and `apikey` correspond
to the values set-up within the service group provisioning stage. In this case the Motion sensor group had been provisioned
as shown:

```json
{
     "apikey":      "1068318794",
     "cbroker":     "http://orion:1026",
     "entity_type": "Motion",
     "resource":    "/iot/d",
}
```


#### 18 Request:

```bash
curl -iX PUT \
  'http://localhost:4041/iot/services?resource=/iot/d&apikey=1068318794' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
     "cbroker": "http://orion-proxy:1027",
     "trust": "30a5ce4c71e416bd199dcdcb7f8bcd8d70e8bb5e"
}'
```

The Motion sensor requests are now sent via the `orion-proxy` and identify themselves using the generated trust token.

**Comment by jason-fox** [comment]
README updated and clarified. Closing.

**Comment by cxzero** [comment]
Thanks Jason for the quick reply! I was checking and it seems to be working fine.

After provisioning the sensor and checking through orion-proxy, it returns the entity:

```
curl -s -X GET   'http://localhost:1027/v2/entities/urn:ngsi-ld:Motion:001?type=Motion'   \
   -H 'fiware-service: openiot'   \
   -H 'fiware-servicepath: /'   \
   -H 'X-Auth-Token: ec02ea9c432e866a0312ecd9939ccc16d433129e'
```
```
{
  "id": "urn:ngsi-ld:Motion:001",
  "type": "Motion",
  "TimeInstant": {
    "type": "DateTime",
    "value": "2021-02-26T13:05:16.784Z",
    "metadata": {}
  },
  ...
  "count": {
    "type": "Integer",
    "value": null,
    "metadata": {}
  },
  "function": {
    "type": "Text",
    "value": [
      "sensing"
    ],
    "metadata": {}
  },
  "refStore": {
    "type": "Relationship",
    "value": "urn:ngsi-ld:Store:001",
    "metadata": {}
  },
 ...
}

```

Appreciate your help!
Regards,
Juan

**Comment by cxzero** [comment]
Just to notice for someone facing similar issues, if the `trust token` specified in [group provisioning](https://github.com/FIWARE/tutorials.PEP-Proxy#iot-agent---provisioning-a-trusted-service-group) is invalid or is not correct, I got this error in the [sensor provisioning](https://github.com/FIWARE/tutorials.PEP-Proxy#iot-agent---provisioning-a-sensor):

`{"name":"ENTITY_GENERIC_ERROR","message":"Error accesing entity data for device: motion001 of type: Motion"}`

So, issuing a new permanent token and updating the provisioning group should be fine.
