### ISSUE TITLE
"Cannot read property 'includes' of undefined" 

### ISSUE THREAD

**Issue by zeldalegends** [Fiware/tutorials.PEP-Proxy#22]
After the commit of the new version of Keyrock, the following call is broken:

http://{{keyrock}}/oauth2/token

Response code 503, payload "Cannot read property 'includes' of undefined" 

Before the update, the call gave the token correctly.

("Keyrock - User Obtains an Access Token" in Postman collection)

**Comment by jason-fox** [comment]
The **Keyrock** version for the tutorial is defined [here](https://github.com/FIWARE/tutorials.PEP-Proxy/blob/master/.env#L22) - are you saying that the `8.1.0` stable release of **Keyrock** is defective or are you running against a canary build like `latest` ? Either way this is a bug which should be raised as a [Keyrock Issue](https://github.com/ging/fiware-idm/issues). 

If `8.1.0` is indeed in error, then this tutorial will need to revert back to `8.0.0`

**Comment by zeldalegends** [comment]
Exactly. I fear the changes in the underlying MySQL db broke the tests. Empirically, I found that the only option is to revert to Orion LD v1.0.1 with Keyrock v7.9.2, because the newer versions do not work properly together.

**Comment by jason-fox** [comment]
It looks like an issue has already been [raised](https://github.com/ging/fiware-idm/issues/259), and I think fixed. I just built a canary docker image based on latest `master` and it worked fine for me. The Keyrock team just need to make a release - maybe  @apozohue10 can help?
