### ISSUE TITLE
Internal server error when trying to provison a device

### ISSUE THREAD

**Issue by husqD** [Fiware/tutorials.PEP-Proxy#9]
Hello, I have followed all the steps in the tutorial and in the final API request i have this error:

curl -iX POST \
  'http://localhost:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion001",
     "entity_name": "urn:ngsi-ld:Motion:001",
     "entity_type": "Motion",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "c", "name": "count", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Store:001"}
     ]
   }
 ]
}
'
**HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Fiware-Correlator: 37f30ba4-f8c6-4b5d-84e5-d64a977583d8
Content-Type: application/json; charset=utf-8
Content-Length: 112
ETag: W/"70-xOM1tLs5I4+bVMnjg3ALyD6cnrY"
Date: Mon, 25 Jan 2021 12:32:44 GMT
Connection: keep-alive

{"name":"SECURITY_INFORMATION_MISSING","message":"Some security information was missing for device type:Motion"}%**

All the previous steps are okey, and i have tried twice with no success.

**Comment by jason-fox** [comment]
Your issue will be with the payload of the [previous request](https://github.com/FIWARE/tutorials.PEP-Proxy#oneeight-request). You need to ensure that the trust token matches the one created in Keyrock.

Note that the payload here explicitly refers to  the **Motion** entity type.

```console
curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Motion",
     "resource":    "/iot/d",
     "trust": "e37aeef5d48c9c1a3d4adf72626a8745918d4355"
   }
 ]
}'
```

and without an associated trust token the provisioning will error `SECURITY_INFORMATION_MISSING`

**Comment by cxzero** [comment]
Hi, I am facing the same issue, still generating a trust token like https://github.com/FIWARE/tutorials.PEP-Proxy#oneseven-request.

The steps are:

**1. Generate a permanent token:**
```
curl -X POST \
  http://localhost:3005/oauth2/token \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic dHV0b3JpYWwtZGNrci1zaXRlLTAwMDAteHByZXNzd2ViYXBwOnR1dG9yaWFsLWRja3Itc2l0ZS0wMDAwLWNsaWVudHNlY3JldA==' \
  -d 'username=alice-the-admin@test.com&password=test&grant_type=password&scope=permanent'
```
`{"access_token":"1c385007ea9675490f37e3563fbb0d87fe1cbac8","token_type":"bearer","expires_in":3599,"refresh_token":"66f63fa5f9a6c3013191c15ae248776adc0c68fa","scope":["p"]}`

> In this case the scope is "p" and not "permanent" as in the tutorial, but perhaps it is because of an update in Keyrock 
> I also checked the "Token types" configuration for the "FIWARE Tutorial" app and "Permanent" is selected.

**2. Provision a trusted service group** (with above token)
```
curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Motion",
     "resource":    "/iot/d",
     "trust": "1c385007ea9675490f37e3563fbb0d87fe1cbac8"
   }
 ]
}'
```
> I am curious in this step if the cbroker URL is correct. **Should it be http://orion-proxy:1027?** 
> I changed it, but the error persists.

**3. IoT Agent - provisioning a sensor (error)**
```
curl -iX POST \
  'http://localhost:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "motion001",
     "entity_name": "urn:ngsi-ld:Motion:001",
     "entity_type": "Motion",
     "timezone":    "Europe/Berlin",
     "attributes": [
       { "object_id": "c", "name": "count", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Store:001"}
     ]
   }
 ]
}
'
```
`{"name":"SECURITY_INFORMATION_MISSING","message":"Some security information was missing for device type:Motion"}`

Thanks in advance!
Regards,
Juan
